---
- name: configuración de elasticsearch
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  notify: reiniciar elasticsearch

- name: configuración del servicio de elasticsearch
  template: src=elasticsearch.j2 dest=/etc/default/elasticsearch owner=root group=root mode=0644
  notify: reiniciar elasticsearch